title: Cam's new Blog
description: BLOGGS

url: ""
baseurl: "/csci340blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Lemurs
    url: /lemur

social:
  github: CamDiM
  email: cam.dimaggio@yahoo.com

google_analytics: "UA-58263416-1"
